# 서버 문 번호
server.port=8080

# 시놀로지 MariaDB 연결 정보
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# 내부 주소(192.168.0.4)를 사용합니다.
spring.datasource.url=jdbc:mariadb://192.168.0.4:3307/smartfish
spring.datasource.username=swmc
spring.datasource.password=Dbekqha!007

# JPA 설정 (DB와 대화하는 법)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp